feat: init token routing
balancednetwork/balanced-network-info pull request #24
Opened 2021-07-18 18:12 UTC by hetfly

2021-07-19 18:30 UTC, hetfly commented
@WeiLi512 
1) token.totalSupply from useAllTokensQuery() shows circulating supply instead of total supply, at least for ICX
2) I need to get info about tokens 24h volume, can you point me to some docs where I can find out how ?
thanks

2021-07-21 19:23 UTC, hetfly commented
@parrot9design  @WeiLi512  please review,
we are missing ICX total supply and 24h volume for all tokens,
I assume total supply is the same as circulating supply for BALN, sICX a bnUSD.
Do we ship as is or do we wait ?

2021-07-22 02:59 UTC, parrot9design requested changes
>we are missing ICX total supply and 24h volume for all tokens,
I assume total supply is the same as circulating supply for BALN, sICX a bnUSD.

Yep, total and circulating supply will be the same for sICX, BALN, and bnUSD. The ICX total supply and 24h volume for all coins may take a bit more work to pull through, so for now, let's omit the third line of data and change `Total supply` -> `Circulating supply`:

<img width="408" alt="Screen Shot 2021-07-22 at 2 42 17 PM" src="https://user-images.githubusercontent.com/63842577/126583243-07607978-1f8d-422b-95e7-280ada5057ea.png">

---

In the ICX summary, there's a space where we can show a dynamic ICX reward rate. This figure is already used in the Collateral section on the Stats page:

>  If you stake ICX in a supported wallet, you'll earn regular staking rewards, based on ICON's variable reward rate (currently x% per year). 

---

Let's also get the arrows in place for each of the tokens, to make it clear you can interact with them:

**Current** | **Design**
----------- | ------------
<img width="218" alt="Screen Shot 2021-07-22 at 2 31 28 PM" src="https://user-images.githubusercontent.com/63842577/126582699-f3fa5bf5-63b7-459a-be1f-410a406459b4.png"> |<img width="255" alt="Screen Shot 2021-07-22 at 2 31 23 PM" src="https://user-images.githubusercontent.com/63842577/126582702-2e0f80c5-f4c1-44f6-afa1-1db29c0a8991.png">

---

The summary text is also a bit too large. Let's give it these styles:

```
font-size: 18px;
line-height: 32px;
```

2021-07-22 05:48 UTC, hetfly commented
@parrot9design do you see the links without arrows here as well ? If so, please specify your browser version
https://balanced-network-info-i07pt108g-balanced-dao.vercel.app/

2021-07-22 17:55 UTC, hetfly commented
Updated based on the feedback, but the current staking rewards value in collateral section is a static one. 
I didn't find a way to get it dynamically.

2021-07-24 05:41 UTC, parrot9design commented
> @parrot9design do you see the links without arrows here as well ? If so, please specify your browser version

I see the arrows now. They make the token names harder to read at smaller screen sizes, though – can we increase the width of the asset column to avoid splitting words in half?

**Current** | ** Preferred**
----------- | --------------
<img width="155" alt="Screen Shot 2021-07-23 at 4 12 15 PM" src="https://user-images.githubusercontent.com/63842577/126858413-3faff756-d31a-495b-a8fe-d8e359f47157.png"> | <img width="175" alt="Screen Shot 2021-07-23 at 4 13 47 PM" src="https://user-images.githubusercontent.com/63842577/126858415-37092fc4-3196-4dff-8af3-19c0e814b7b5.png">

---

> the current staking rewards value in collateral section is a static one.
I didn't find a way to get it dynamically.

That I wasn't aware of, thanks for bringing it to my attention! It looks like you've found a way to get it dynamically now? Where are you pulling the data from?

2021-07-25 18:14 UTC, hetfly commented
Token name width is fixed,
staking rewards are still static, I just updated the current value.

2021-07-26 04:56 UTC, parrot9design commented
This is great, thanks @hetfly. I've opened an issue to get the ICX staking apy resolved: https://github.com/balancednetwork/balanced-network-info/issues/29

Ideally I would like to get that implemented before we publish this, to minimise the number of static data points we need to maintain.

2021-07-29 04:03 UTC, WeiLi512 requested changes

2021-07-29 04:03 UTC, WeiLi512 commented on src/pages/TokenPage/index.tsx
> +const Container = styled(Box)`
I can see some same components(`Container`, `CurrencyIcon`,..) used in the codebase. Please DRY the code as you can do.

2021-08-23 03:33 UTC, parrot9design commented
@hetfly it looks like we have a dynamic APY for ICX staking now: https://github.com/balancednetwork/balanced-network-info/pull/34

2021-08-31 19:55 UTC, parrot9design commented on src/components/TokenDetails/ICXDetail.tsx
> +          {`On Balanced, you can use ICX as collateral to borrow synthetic assets, like Balanced Dollars.`}
```suggestion
          {`On Balanced, you can use ICX as collateral to borrow synthetic assets, like Balanced Dollars. You'll also need to keep at least 1 ICX in your wallet at all times to cover transaction fees.`}
```

2021-08-31 19:56 UTC, parrot9design commented on src/components/TokenDetails/SICXDetail.tsx
> +          {`With sICX, you can unstake faster than traditional ICX unstaking. Pay a 1% premium to swap sICX for ICX, or unstake from the wallet section to join the unstaking queue, which could take a
```suggestion
          {`With sICX, you can unstake faster than traditional ICX unstaking. Pay a 1% premium to swap sICX for ICX on Balanced, or unstake from the wallet section to join the unstaking queue, which could take anywhere from 5 minutes, up to the regular ICX unstaking time of ~7 days.`}
```

2022-06-22 01:15 UTC, BennyOptions commented
Not going to work on this for now

2022-06-22 01:15 UTC, closed without merging