feat: 🎸 header and footer
balancednetwork/balanced-network-info pull request #8
Opened 2021-06-14 14:33 UTC by hieunguyenebox

2021-06-15 14:08 UTC, hieunguyenebox commented
@WeiLi512  plz review

2021-06-15 22:29 UTC, WeiLi512 requested changes
Please make UI the same as the prototype. If then, please request to review.

2021-06-15 22:29 UTC, WeiLi512 commented on package.json
> +    "styled-components-breakpoint": "3.0.0-preview.20",
Where did you use this module?

2021-06-15 22:29 UTC, WeiLi512 commented on src/assets/images/logo.svg
> +<svg clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 678 500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><radialG
Please move all svg icons to 'assets/icons' directory.

2021-06-15 22:29 UTC, WeiLi512 commented on src/components/uikit/AnimatedLink.tsx
> +import styled from 'styled-components';
Just put the UI components in the `components` directory for now.

2021-06-17 13:21 UTC, hieunguyenebox commented
@WeiLi512  plz check again

2021-06-22 08:28 UTC, parrot9design requested changes
### Header

**Current** | [**Design**](http://balanced-development.s3-website-us-east-1.amazonaws.com/stats/)
----------- | -------------
<img width="1242" alt="Screen Shot 2021-06-22 at 8 14 01 PM" src="https://user-images.githubusercontent.com/63842577/122889809-3bb25f00-d397-11eb-8f22-762856f4294b.png"> | <img width="1257" alt="Screen Shot 2021-06-22 at 8 14 07 PM" src="https://user-images.githubusercontent.com/63842577/122889841-4240d680-d397-11eb-8617-28ab410b5bf2.png">

- Give the logo a width of 100px
- Make the navigation items 16px
- Include the page title `Statistics`
- Remove `Overview` from the first section
-  Fix the transparency of the total value locked icon



### Footer

**Current** | [**Design**](http://balanced-development.s3-website-us-east-1.amazonaws.com/stats/)
----------- | -------------
<img width="1250" alt="Screen Shot 2021-06-22 at 8 21 49 PM" src="https://user-images.githubusercontent.com/63842577/122890134-8633db80-d397-11eb-89c7-e3ab9d3142f6.png"> | <img width="1251" alt="Screen Shot 2021-06-22 at 8 21 59 PM" src="https://user-images.githubusercontent.com/63842577/122890174-8df38000-d397-11eb-8e0d-80f908c0bbe8.png">

- Add the divider line 
- Give the logo a width of 100px
- Make the navigation items 16px

2021-06-24 03:02 UTC, parrot9design commented
The logo and navigation sizing looks much better. 👍 

The overview and governance sections still need a few adjustments:

**Current** | [**Design**](http://balanced-development.s3-website-us-east-1.amazonaws.com/stats/)
----------- | -------------
![Screen Shot 2021-06-24 at 3 00 37 PM](https://user-images.githubusercontent.com/63842577/123195881-0293ff00-d4fd-11eb-8494-82d902e4e40b.png) | <img width="1257" alt="Screen Shot 2021-06-22 at 8 14 07 PM" src="https://user-images.githubusercontent.com/63842577/122889841-4240d680-d397-11eb-8617-28ab410b5bf2.png">

- Include the page title `Statistics`
- Remove the `Overview` heading
- Fix the transparency of the total value locked icon
- Remove the bold style from the values (should be a normal weight)



### Footer

**Current** | [**Design**](http://balanced-development.s3-website-us-east-1.amazonaws.com/stats/)
----------- | -------------
![Screen Shot 2021-06-24 at 3 00 44 PM](https://user-images.githubusercontent.com/63842577/123195907-0f185780-d4fd-11eb-9e47-28afc2af4d0c.png) | ![Screen Shot 2021-06-24 at 3 00 51 PM](https://user-images.githubusercontent.com/63842577/123195923-13dd0b80-d4fd-11eb-90e3-a3ed0367a772.png)


- Remove the bold style from the values (should be a normal weight)

2021-06-26 09:48 UTC, parrot9design commented
To recap:

1. The transparency of the TVL icon needs fixed (I believe it’s isolated to this PR)
2. The overview and governance stats need the bold style removed
3. We need to add `Stats` to the navigation:

Top of page
![3F5AB1C8-C3B2-4717-BC87-763CBEC8DEDC](https://user-images.githubusercontent.com/63842577/123509165-07f17500-d6c8-11eb-8c31-e93fbc2009ca.jpeg)

Bottom of page
![A394CD3F-2002-48CB-93A1-108E79E55778](https://user-images.githubusercontent.com/63842577/123509176-10e24680-d6c8-11eb-88df-b0c49f30a6d9.jpeg)

@WeiLi512 @hieunguyenebox Let’s make sure this PR makes it into tomorrow’s release.

2021-06-26 14:50 UTC, hieunguyenebox commented
@parrot9design all fixed, please check

2021-06-26 21:01 UTC, parrot9design commented
Looks good! Just need to make the underline active for the stats link so people know it's the active page.

Example:

![Screen Shot 2021-06-27 at 9 01 29 AM](https://user-images.githubusercontent.com/63842577/123525632-4cabf900-d726-11eb-9a04-f132274fa1a4.png)
![Screen Shot 2021-06-27 at 9 01 26 AM](https://user-images.githubusercontent.com/63842577/123525633-4ddd2600-d726-11eb-9b8b-8510ad1130bb.png)

2021-06-26 23:58 UTC, WeiLi512 requested changes

2021-06-26 23:58 UTC, WeiLi512 commented on src/sections/PairSection.tsx
> +      <Box overflow="scroll">
Instead of wrapping with `Box`, please customize `List` component.

2021-06-26 23:58 UTC, WeiLi512 commented on src/sections/TokenSection.tsx
> +      <Box sx={{ overflow: 'scroll' }}>
Instead of wrapping with `Box`, please customize `List` component.

2021-06-27 00:32 UTC, merged