fix: fix loan baln rewards calculation
balancednetwork/balanced-network-info pull request #94
Opened 2022-02-08 18:09 UTC by hetfly

close #91

2022-02-09 05:38 UTC, parrot9design approved these changes
I think this works from a UI perspective? Stats.balanced.network seems to be reporting the right amount of borrower rewards now (12.5%), so it's a little hard to judge.

2022-03-01 07:24 UTC, octocat512 requested changes

2022-03-01 07:24 UTC, octocat512 commented on src/queries/index.ts
> +export function useBalnAllocation() {
I'd like you to use `react-query`. It will reduce and simplify the code. @hetfly

2022-03-01 07:25 UTC, octocat512 commented
Please resolve the conflicts. @hetfly

2022-03-01 14:13 UTC, merged